### ISSUE TITLE
Black screen when playing in Polish/loading screen freeze

### ISSUE THREAD

**Issue by f7cjo** [AeroWidescreen/NFSMW2012HDEffects#3]
When I try to run the game with the mod installed and the official Steam Polish translation, the game gets stuck on a black screen without any title screen on anything, with a debug.log file creating with one line repeating.
[debug.log](https://github.com/AeroWidescreen/NFSMW2012HDEffects/files/6824855/debug.log)
Then I changed the language to English using the Steam language picker and it went past the title screen but freezes on the loading screen after less than a second with the music still playing, with no debug.log file creating.
![obraz](https://user-images.githubusercontent.com/71151647/125825708-46315f0e-e87c-4bf2-bb5c-55c72d859393.png)
My executable version is 1.5.0.0

**Comment by AeroWidescreen** [comment]
Hi, open the INI file and change these settings to 0. Tell me if it makes a difference.

> [MAIN]
> Gameplay = 0       // Determines if the entire GAMEPLAY section is enabled or disabled.
> General = 0          // Determines if the entire GENERAL section is enabled or disabled.

Unfortunately, I don't have the Steam version, only the Origin version. I was hoping it would go on sale for the summer, but it was the only Need for Speed game that didn't. Could you believe that? Weird. I've heard people having trouble with Steam version before and wanted to investigate, but I have no cash to spend on video games at the moment.

**Comment by f7cjo** [comment]
After disabling these settings the game loads in and works, but I'm not sure the mod loads in.
Asi loader present
![obraz](https://user-images.githubusercontent.com/71151647/125831666-75c1a78f-7105-4c0c-b0ed-575d32b62743.png)
Asi loader absent
![obraz](https://user-images.githubusercontent.com/71151647/125832061-bf887fd2-e2ca-42fb-a6c2-9824deaf4bce.png)

**Comment by AeroWidescreen** [comment]
Okay, good. Could you please follow these troubleshooting steps? Tell me when the game starts to crash for you again. Part 1? Part 2? No crash at all?

---

Troubleshoot Part 1: Enable `Gameplay` section. Does the game still work? Proceed to Part 2.

> [MAIN]
> Gameplay = 1 // Determines if the entire GAMEPLAY section is enabled or disabled.

---

Troubleshoot Part 2: Enable `General` section and _disable_ `AutoRefreshGraphics`.

> [MAIN]
>General = 1 // Determines if the entire GENERAL section is enabled or disabled.

> [GENERAL]
> AutoRefreshGraphics = 0  // Solves an issue that caused grass, bushes, and trees to not render until the resolution was changed.

Does the game still work?

**Comment by AeroWidescreen** [comment]
>but I'm not sure the mod loads in.

You can test this by using one of the Hotkeys. For example: Press F8 to change the time of day.

**Comment by f7cjo** [comment]
After troubleshoot part 1 game still loads and works fine, and the daytime hotkey works perfectly. After troubleshoot part 2 game still works.
![obraz](https://user-images.githubusercontent.com/71151647/125834940-21ad1af1-a25d-4592-b828-6f19afbe88a8.png)
Screenshot taken after part 2

**Comment by AeroWidescreen** [comment]
That means `AutoRefreshGraphics` is the problem. Thankfully this feature isn't as important as the others. You can get the same results by changing your resolution in the options menu. You'll have to do this every time you start the game... but that's what `AutoRefreshGraphics` was supposed to do for you. If you don't do this you'll be missing out on a lot of detail the game doesn't render. 

Anyway, like I said, I don't have money to buy the Steam version so I can't fix anything right now. I'll look into it when I can. Thanks for your help.

**Comment by hrjohn** [comment]
How exactly did you change the language? Did you use the steam language option?
Since the game still relies on Origin, you could try re-installing the game through origin and selecting Polish as main language.
Another alternative would be to change the registry key of the language, but in this case, you'll need the language files as well(not usually bundled with the game on install)

**Comment by AeroWidescreen** [comment]
> Since the game still relies on Origin, you could try re-installing the game through origin and selecting Polish as main language.

I did this exact thing with my Origin install: Polish language, AutoRefreshGraphics enabled, no crashes, no trouble. I assumed it had something to do with his Steam install. Hopefully he'll reply.

**Comment by AeroWidescreen** [comment]
Alright, so I have the Steam version and I still can't reproduce this bug. Polish language and all. As far as I can tell, the Origin and Steam binaries are identical, down to the very last byte. I'm honestly disappointed.

**Comment by f7cjo** [comment]
I realized later that the language is unrelated, my game was just acting up and randomly not working, and a reinstall fixed it
