### ISSUE TITLE
Can this be configured on a Steam Deck

### ISSUE THREAD

**Issue by SecularSteve** [AeroWidescreen/NFSMW2012HDEffects#5]
Tried it so far, and nothing's working for me.

I don't think the "steamapps/common" is the same for Linux/Proton users.

Any advice?

**Comment by AeroWidescreen** [comment]
dinput8.dll and the scripts folder should be in the same place as **NFS13.exe**. That's my only advice, I don't have a Steam Deck.

**Comment by 7HEPOW** [comment]
It basically works the same as on Windows, BUT you need to modify the launch parameters in the game's preferences to:
```WINEDLLOVERRIDES="dinput8.dll=n,b" %command%```
This way you're telling Proton (or Wine) to load the dll files present in the excutable's folder first and then load the systems dll files.
Whenever using drop in dll files like this or for widescreen fixes and such, this is the way to do it 😉

**Comment by SecularSteve** [comment]
Thanks buddy!
This did the trick. Got a stuttery 45-55 FPS if I max it out (minus the supersampling, unless 2x at a mostly stable stuttery 35 FPS is your vocation).

So I've capped it to 30 using the Deck limiter.

I honestly do wonder why they've never bothered to include an official in-game 30/60 cap like in Hot Pursuit.

For console authenticity and all that. So the menus can play at 60 too.
